system:
  networkName: 'Whacker Net' #Network name
  networkBindAddress: '0.0.0.0' #Bind to address for the network
  networkBindPort: 3000 #Bind to port for the network

  controlChannels: #Multiple control channels work, but don't touch any of this for now. It is static in the client file.
    - "854.9625"
    - "857.9625" #You will not see this ever active by default at this time. Again, don't touch control channels.

  voiceChannels: #Have as many as you want and your hosting server can handle. If all voice channels are in use, radios will get denied.
    - "853.9625"
    - "855.9625"

paths:
  fullPath: '/home/user/whackerlink' #FULL path to whackerlink
  rconLogins: './rcon_logins.json' #FULL path to json rcon logins
  sheetsJson: './something-124.json' #FULL path to the google sheets json file
  httpsEnable: true #Do not change unless going through a proxy. This will NOT work unless it is https

configuration:
  sheetId: '' #Sheet ID for the google sheet
  grantDenyOccurrence: 5 #How often people will get random grant denys. Higher the number less often. Lowest number is 3.
  discordWebHookEnable: false #Enable discord functions
  discordWebHookUrl: '' #Webhook URL
  httpsEnable: true #Do not change unless going through a proxy. This will NOT work unless it is https
  apiEnable: false #Recommned leaving disabled for now
  apiToken: "biglongtoken" # MAKE SURE TO MAKE THIS SECURE
  socketAuthToken: "" # Make sure to run the token generator to fill in this value

peer: #Currently WIP no need to touch
  externalPeerEnable: false #Enable external software peering
  username: 'whacker' #Username for peer to login to
  password: 'link' #Password for peer to login to
  rid: '9998'
  channel: 'Main'
  metaData: true #Pass pages, emergency, etc
  rconEnable: true #Allow RCON functions from the peer

discord:
  voiceGrant: true
  voiceRequest: true
  voiceDeny: true
  affiliationGrant: true
  affiliationDeny: true
  regGrant: true
  regRequest: true
  regDeny: true
  regRefuse: true
  page: true
  inhibit: true
  emergencyCall: true
