system:
  networkName: 'Whacker Net' #Network name
  networkBindAddress: '0.0.0.0' #Bind to address for the network
  networkBindPort: 3000 #Bind to port for the network

paths:
  fullPath: '/home/user/whackerlink' #FULL path to whackerlink
  rconLogins: './rcon_logins.json' #FULL path to json rcon logins
  sheetsJson: './something-124.json' #FULL path to the google sheets json file

configuration:
  sheetId: '' #Sheet ID for the google sheet
  grantDenyOccurrence: 5 #How often people will get random grant denys. Higher the number less often. Lowest number is 3.
  discordWebHookEnable: false #Enable discord functions
  discordWebHookUrl: '' #Webhook URL

peer: #Currently WIP no need to touch
  externalPeerEnable: false #Enable external software peering
  username: 'whacker' #Username for peer to login to
  password: 'link' #Password for peer to login to
  rid: '9998'
  channel: 'Main'
  metaData: true #Pass pages, emergency, etc
  rconEnable: true #Allow RCON functions from the peer

discord:
  voiceGrant: true
  voiceRequest: true
  voiceDeny: true
  affiliationGrant: true
  affiliationDeny: true
  regGrant: true
  regRequest: true
  regDeny: true
  page: true
  inhibit: true
  emergencyCall: true
